using SephiriaOne;
using Mirror;

int passed = 0, failed = 0;
void Check(string name, Action action) { try { Reset(); action(); Console.WriteLine("PASS " + name); passed++; } catch (Exception e) { Console.WriteLine("FAIL " + name + ": " + e.Message); failed++; } }
void Assert(bool ok, string reason) { if (!ok) throw new Exception(reason); }
void Throws(Action action) { try { action(); } catch (InvalidOperationException) { return; } throw new Exception("Expected safe refusal"); }
void Reset() { NetworkServer.active = true; NetworkServer.connections.Clear(); ResourceRuntime.Managed.Clear(); ResourceRuntime.Messages.Clear(); ResourceRuntime.Apply = null; ResourceRuntime.Calls = 0; ResourceRuntime.Restored = 0; SessionSettings.Faults = 0; SessionSettings.ResourceWritesBlocked = false; SessionSettings.ResourceGeneration = 0; KeywordDatabase.FruitBase = 6; PassiveDatabase.data.Clear(); PassiveDatabase.data.Add(1, new PassiveEntity { id = 1 }); PassiveDatabase.data.Add(2, new PassiveEntity { id = 2 }); PlayerSpawner.MultiplayerList.Clear(); SaveManager.CurrentRun = new(); UIManager.Instance = null; }
ResourceUpdate Update(ResourceKind kind, int raw, int owned, int target) => new(ResourceCatalog.Get(kind), raw, owned, target);
PlayerAvatar.PassiveStatSaveData Pick(ulong id, int point) => new() { id = id, point = point };
void Piece(PlayerAvatar p, int weight = 1) => p.localDataStorage.fruitSkewerBonus.Add(new() { categoryName = "same", weight = weight });
void Connect(PlayerAvatar p) => NetworkServer.connections.Add((int)p.netId, new NetworkConnectionToClient { identity = new NetworkIdentity { Player = p } });

Check("Talent snapshot captures total, owner marker and spent", () => { var p = new PlayerAvatar { maxPassivePoint = 12 }; p.passiveStats.Add(1, 4); p.passiveStats.Add(2, 2); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 7; var s = ResourceBudgets.Capture(p, ResourceKind.Talents); Assert(s.Raw == 12 && s.Owned == 7 && s.MinimumSafe == 6 && !s.Busy, "Wrong talent snapshot"); });
Check("Fruit counts pieces rather than categories or sign and reserves adaptive", () => { var p = new PlayerAvatar(); Piece(p); Piece(p); Piece(p, -1); p.localDataStorage.adaptiveItemDropBonus = 3; p.customStats["FRUITCOUNT"] = 4; p.calculatedBonusStats["FRUITCOUNT"] = 2; p.customStatsAmp["FRUITCOUNT"] = 50; p.localDataStorage.preparingUIThings = true; var s = ResourceBudgets.Capture(p, ResourceKind.Fruit); Assert(s.Raw == 4 && s.Bonus == 2 && s.Amplifier == 50 && s.DisplayOffset == 6 && s.MinimumSafe == 4 && s.Busy, "Wrong fruit snapshot"); });
Check("Host panel busy flag does not prevent host reduction", () => { var p = new PlayerAvatar { isOwned = true }; p.localDataStorage.doingSomeUIThings = true; Assert(!ResourceBudgets.Capture(p, ResourceKind.Fruit).Busy, "Host generic UI flag counted"); });
Check("Talent decrease refuses spent selections and writes nothing", () => { var p = new PlayerAvatar { maxPassivePoint = 10 }; p.passiveStats[1] = 7; var b = new StateWriteBatch(() => true); Throws(() => ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Talents, 6, 1, 6))); Assert(p.maxPassivePoint == 10 && p.customStats.Count == 0, "Mutation before preflight"); });
Check("Guest fruit UI refuses reduction but permits increase", () => { var p = new PlayerAvatar(); p.localDataStorage.preparingUIThings = true; Throws(() => ResourceBudgets.AddWrites(new(() => true), p, Update(ResourceKind.Fruit, -1, -1, 5))); var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Fruit, 2, 2, 8)); Assert(b.TryCommit(out var e), e); });
Check("Talent writer uses cap setter and removes only zero owner marker", () => { var p = new PlayerAvatar { maxPassivePoint = 12 }; p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 7; int writes = 0; p.AfterCapWrite = () => writes++; var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Talents, 5, 0, 5)); Assert(b.TryCommit(out var e), e); Assert(p.maxPassivePoint == 5 && writes == 1 && p.customStats.Count == 0, "Wrong cap/marker write"); });
Check("Fruit writes raw contribution preserving native bonus and pieces", () => { var p = new PlayerAvatar(); Piece(p); p.calculatedBonusStats["FRUITCOUNT"] = 2; p.customStatsAmp["FRUITCOUNT"] = 50; var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Fruit, 4, 4, 15)); Assert(b.TryCommit(out var e), e); Assert(p.customStats["FRUITCOUNT"] == 4 && p.GetCustomStatUnsafe("FRUITCOUNT") + 6 == 15 && p.localDataStorage.fruitSkewerBonus.Count == 1, "Wrong fruit mutation"); });
Check("Precommit allocation drift refuses budget write", () => { var p = new PlayerAvatar { maxPassivePoint = 10 }; var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Talents, 6, 1, 6)); p.passiveStats[1] = 7; Assert(!b.TryCommit(out _) && p.maxPassivePoint == 10, "Stale allocation accepted"); });
Check("Precommit same-count guest composition edit is detected", () => { var p = new PlayerAvatar(); Piece(p); var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Fruit, 2, 2, 8)); p.localDataStorage.fruitSkewerBonus[0] = new() { categoryName = "changed", weight = -1 }; Assert(!b.TryCommit(out _) && !p.customStats.ContainsKey("FRUITCOUNT"), "Stale composition accepted"); });
Check("Postwrite native bonus drift is not reported as success", () => { var p = new PlayerAvatar { maxPassivePoint = 10 }; p.AfterCapWrite = () => p.passiveStats[1] = 9; var b = new StateWriteBatch(() => true); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Talents, 6, 1, 6)); Assert(!b.TryCommit(out _) && b.MayHaveWritten, "Postwrite drift accepted"); });
Check("Incoming talent load respects per-entry cap, duplicates and unknown ids", () => { var p = new PlayerAvatar(); p.passiveStats[1] = 2; int n = ResourceBudgets.RequiredTalentLoad(p, new[] { Pick(1, 10), Pick(1, 15), Pick(2, 3), Pick(999, 999) }); Assert(n == 23, "Wrong incoming allocation minimum: " + n); });
Check("Incoming load keeps peak allocation across native database ordering", () => { var p = new PlayerAvatar(); p.passiveStats[2] = 10; int n = ResourceBudgets.RequiredTalentLoad(p, new[] { Pick(2, -10), Pick(1, 10) }); Assert(n == 20, "Only final allocation checked"); });
Check("Invalid negative spent selection fails safe", () => { var p = new PlayerAvatar(); p.passiveStats[1] = -1; Throws(() => ResourceBudgets.Capture(p, ResourceKind.Talents)); });
Check("Talent recovery refuses allocations added after another write failed", () => { var p = new PlayerAvatar { maxPassivePoint = 10 }; int prior = 0; var b = new StateWriteBatch(() => true); b.Add("earlier failure", () => prior, n => { prior = n; throw new InvalidOperationException(); }, 1); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Talents, 6, 1, 6)); Assert(!b.TryCommit(out _), "Expected initial partial batch"); p.passiveStats[1] = 7; Assert(!b.TryRecover(out _) && p.maxPassivePoint == 10, "Recovery lowered cap below new allocations"); });
Check("Fruit recovery refuses newly committed selections before raw write", () => { var p = new PlayerAvatar(); int prior = 0; var b = new StateWriteBatch(() => true); b.Add("earlier failure", () => prior, n => { prior = n; throw new InvalidOperationException(); }, 1); ResourceBudgets.AddWrites(b, p, Update(ResourceKind.Fruit, -1, -1, 5)); Assert(!b.TryCommit(out _), "Expected initial partial batch"); for (int i = 0; i < 6; i++) Piece(p); Assert(!b.TryRecover(out _) && !p.customStats.ContainsKey("FRUITCOUNT"), "Recovery lowered fruit budget before checking selections"); });

Check("Hooks install and native saved load sees raised budget before its body", () => { ResourceBudgetHooks.Install(); Assert(ResourceBudgetHooks.Available, "Hooks unavailable"); var p = new PlayerAvatar(); ResourceRuntime.Managed.Add(ResourceKind.Talents); ResourceRuntime.Apply = (player, kind, minimum) => player.maxPassivePoint = minimum; p.LoadPassiveStatOnServer(new[] { Pick(1, 10) }); Assert(p.NativeLoadCalls == 1 && p.maxPassivePoint == 10, "Budget not applied before load"); });
Check("Unsafe managed talent load throws before native selections mutate", () => { var p = new PlayerAvatar(); ResourceRuntime.Managed.Add(ResourceKind.Talents); Throws(() => p.LoadPassiveStatOnServer(new[] { Pick(1, 10) })); Assert(p.NativeLoadCalls == 0 && ResourceRuntime.Messages.Count > 0, "Load continued or no error reported"); });
Check("Unmanaged native talent load is unchanged", () => { var p = new PlayerAvatar(); p.LoadPassiveStatOnServer(new[] { Pick(1, 10) }); Assert(p.NativeLoadCalls == 1, "Vanilla native load blocked"); });
Check("Managed fruit zero with a selected piece blocks native grant entirely", () => { var p = new PlayerAvatar(); Piece(p); p.customStats["FRUITCOUNT"] = -6; Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); var d = new DungeonManager(); Throws(() => d.LoadStageAndMove("dungeon")); Assert(d.NativeCalls == 0, "Native first piece leaked at zero"); });
Check("Managed fruit zero empty composition is valid", () => { var p = new PlayerAvatar(); p.customStats["FRUITCOUNT"] = -6; Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); var d = new DungeonManager(); d.LoadStageAndMove("dungeon"); Assert(d.NativeCalls == 1, "Empty zero grant blocked"); });
Check("Adaptive alone requires one budget slot", () => { var p = new PlayerAvatar(); p.customStats["FRUITCOUNT"] = -6; p.localDataStorage.adaptiveItemDropBonus = 1; Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); var d = new DungeonManager(); Throws(() => d.LoadStageAndMove("dungeon")); Assert(d.NativeCalls == 0, "Adaptive free grant accepted"); });
Check("First departure applies policy before grant but later stage does not replay", () => { var p = new PlayerAvatar(); for (int i = 0; i < 8; i++) Piece(p); Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); ResourceRuntime.Apply = (player, kind, minimum) => player.customStats["FRUITCOUNT"] = 2; var d = new DungeonManager(); d.LoadStageAndMove("dungeon"); int before = ResourceRuntime.Calls; d.isRunStarted = true; d.LoadStageAndMove("next"); Assert(d.NativeCalls == 2 && before == 2 && ResourceRuntime.Calls == 2, "Bad first-entry scope"); });
Check("Exact fruit read reapplies dynamic policy after native starting gear", () => { var p = new PlayerAvatar(); Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); ResourceRuntime.Apply = (player, kind, minimum) => player.customStats["FRUITCOUNT"] = 2; var d = new DungeonManager { BeforeFruitRead = () => p.customStats["FRUITCOUNT"] = 0 }; d.LoadStageAndMove("dungeon"); Assert(d.LastFruitTotal == 8, "Consumer read stale budget"); });
Check("Exact fruit read stops new under-budget state after native transition begins", () => { var p = new PlayerAvatar(); Piece(p); Connect(p); ResourceRuntime.Managed.Add(ResourceKind.Fruit); var d = new DungeonManager { BeforeFruitRead = () => p.customStats["FRUITCOUNT"] = -6 }; Throws(() => d.LoadStageAndMove("dungeon")); Assert(d.NativeCalls == 1 && ResourceRuntime.Messages.Any(m => m.Contains("already")), "Missing partial-native warning"); });
Check("Unmanaged corrupt native talent data remains native behavior", () => { var p = new PlayerAvatar(); p.passiveStats[1] = -1; p.LoadPassiveStatOnServer(new[] { Pick(1, 10) }); Assert(p.NativeLoadCalls == 1, "Unmanaged native load intercepted"); });
Check("Guests bypass all authoritative budget hooks", () => { NetworkServer.active = false; var p = new PlayerAvatar(); ResourceRuntime.Managed.Add(ResourceKind.Talents); p.LoadPassiveStatOnServer(new[] { Pick(1, 10) }); var d = new DungeonManager(); d.LoadStageAndMove("dungeon"); Assert(ResourceRuntime.Calls == 0 && p.NativeLoadCalls == 1 && d.NativeCalls == 1, "Guest hook changed native behavior"); });
Check("Uninstall removes owned hooks", () => { ResourceBudgetHooks.Uninstall(); Assert(!ResourceBudgetHooks.Available, "Available remains true"); var p = new PlayerAvatar(); ResourceRuntime.Managed.Add(ResourceKind.Talents); p.LoadPassiveStatOnServer(new[] { Pick(1, 10) }); Assert(p.NativeLoadCalls == 1 && ResourceRuntime.Calls == 0, "Hook survived uninstall"); });
Check("Slots minimum protects last occupied position and excludes potion row", () => { var p = new PlayerAvatar(); p.Inventory.CurrentInventoryStorage = 48; p.Inventory.inventoryMatrix[new(0, 6)] = new(); p.Inventory.inventoryMatrix[new(0, 100)] = new(); p.Inventory.mysticPositions.Add(new(2, 7)); var s = InventoryResources.Capture(p); Assert(s.Raw == 48 && s.MinimumSafe == 45, "Wrong trailing-slot boundary"); });
Check("Occupied shrink refuses before native relocation path", () => { var p = new PlayerAvatar(); p.Inventory.CurrentInventoryStorage = 36; p.Inventory.inventoryMatrix[new(5, 5)] = new(); Throws(() => InventoryResources.AddWrites(new(() => true), p, Update(ResourceKind.Slots, 24, 0, 24))); Assert(p.Inventory.StorageWrites == 0, "Native resize reached before refusal"); });
Check("Engraving or guest pending UI blocks even empty-grid shrink", () => { var p = new PlayerAvatar(); p.Inventory.CurrentInventoryStorage = 36; p.Inventory.engravings.Add(new()); Throws(() => InventoryResources.AddWrites(new(() => true), p, Update(ResourceKind.Slots, 24, 0, 24))); p.Inventory.engravings.Clear(); p.localDataStorage.doingSomeUIThings = true; Throws(() => InventoryResources.AddWrites(new(() => true), p, Update(ResourceKind.Slots, 24, 0, 24))); });
Check("Host generic panel permits resize but native drag blocks it", () => { var p = new PlayerAvatar { isOwned = true }; p.Inventory.CurrentInventoryStorage = 36; p.localDataStorage.preparingUIThings = true; Assert(!InventoryResources.Capture(p).Busy, "Host generic panel blocks command"); UIManager.Instance = new(); UIManager.Instance.Controller.CurrentAny = true; Assert(InventoryResources.Capture(p).Busy, "Native controller drag ignored"); });
Check("Safe capacity write uses native resize and owned marker", () => { var p = new PlayerAvatar(); var b = new StateWriteBatch(() => true); InventoryResources.AddWrites(b, p, Update(ResourceKind.Slots, 36, 12, 36)); Assert(b.TryCommit(out var e), e); Assert(p.Inventory.CurrentInventoryStorage == 36 && p.Inventory.StorageWrites == 1 && p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] == 12, "Wrong native slot write"); });
Check("Inventory drift before commit blocks shrink", () => { var p = new PlayerAvatar(); p.Inventory.CurrentInventoryStorage = 36; var b = new StateWriteBatch(() => true); InventoryResources.AddWrites(b, p, Update(ResourceKind.Slots, 24, 0, 24)); p.Inventory.inventoryMatrix[new(5, 5)] = new(); Assert(!b.TryCommit(out _) && p.Inventory.StorageWrites == 0, "New trailing item was resized away"); });
Check("Inventory recovery refuses a new trailing item before native resize", () => { var p = new PlayerAvatar(); p.Inventory.CurrentInventoryStorage = 36; int prior = 0; var b = new StateWriteBatch(() => true); b.Add("earlier failure", () => prior, n => { prior = n; throw new InvalidOperationException(); }, 1); InventoryResources.AddWrites(b, p, Update(ResourceKind.Slots, 24, 0, 24)); Assert(!b.TryCommit(out _), "Expected initial partial batch"); p.Inventory.inventoryMatrix[new(5, 5)] = new(); Assert(!b.TryRecover(out _) && p.Inventory.StorageWrites == 0 && p.Inventory.CurrentInventoryStorage == 36, "Recovery reached destructive native shrink"); });
Check("Slots hooks install and apply fresh policy once before item enumeration", () => { InventoryResourceHooks.Install(); var p = new PlayerAvatar(); var s = new PlayerSpawner(p); ResourceRuntime.Managed.Add(ResourceKind.Slots); ResourceRuntime.Apply = (player, kind, min) => { player.Inventory.CurrentInventoryStorage = 36; player.customStats[ResourceCatalog.Get(kind).Marker] = 12; }; s.RunInitialize(); Assert(InventoryResourceHooks.Available && s.ReadSlots == 36 && ResourceRuntime.Calls == 1, "Capacity boundary late/repeated"); });
Check("Saved capacity restores before enumeration even after policy removed", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 24; p.customStats.Clear(); s.RunInitialize(); Assert(s.ReadSlots == 36 && p.Inventory.CurrentInventoryStorage == 36 && p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] == 12 && ResourceRuntime.Restored == 1 && ResourceRuntime.Calls == 0, "Checkpoint not restored independently"); });
Check("Repeated initialize does not double own saved capacity", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); s.RunInitialize(); s.RunInitialize(); Assert(s.ReadSlots == 36 && p.Inventory.CurrentInventoryStorage == 36, "Saved capacity compounded"); });
Check("Checkpoint preserves higher new native capacity and owned contribution", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 30; p.customStats.Clear(); s.RunInitialize(); Assert(s.ReadSlots == 42 && p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] == 12, "Native capacity gain lost"); });
Check("Changed future policy cannot shrink checkpoint before restoration", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 24; p.customStats.Clear(); ResourceRuntime.Managed.Add(ResourceKind.Slots); ResourceRuntime.Apply = (player, kind, min) => player.Inventory.CurrentInventoryStorage = 12; s.RunInitialize(); Assert(s.ReadSlots == 36 && ResourceRuntime.Calls == 0 && ResourceRuntime.Restored == 1, "Reduced future policy discarded saved slots"); });
Check("Reused save index with another GUID never inherits old checkpoint", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 24; p.customStats.Clear(); s.playerGuid = "new-player"; s.RunInitialize(); Assert(s.ReadSlots == 24 && ResourceRuntime.Restored == 0, "Checkpoint crossed identity"); });
Check("Unload refuses occupied addon slots and keeps hooks", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; p.Inventory.inventoryMatrix[new(5, 5)] = new(); Throws(() => InventoryResourceHooks.Uninstall()); Assert(InventoryResourceHooks.Available && p.Inventory.CurrentInventoryStorage == 36, "Unsafe unload proceeded"); });
Check("Partially joined unowned peer does not block unload", () => { var p = new PlayerAvatar(); _ = new PlayerSpawner(p); p.Inventory = null; InventoryResourceHooks.Uninstall(); Assert(!InventoryResourceHooks.Available, "Unowned incomplete peer blocked unload"); InventoryResourceHooks.Install(); });
Check("Restore failure after native resize records partial-write fault", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 24; p.customStats.Clear(); p.Inventory.AfterStorageWrite = () => p.netId++; Throws(() => s.RunInitialize()); Assert(SessionSettings.Faults == 1 && p.Inventory.CurrentInventoryStorage == 36 && s.ReadSlots == 0, "Partial restore was not faulted before item reads"); });
Check("Unload failure after native resize records partial-write fault and retains hooks", () => { var p = new PlayerAvatar(); _ = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; p.Inventory.AfterStorageWrite = () => p.netId++; Throws(() => InventoryResourceHooks.Uninstall()); Assert(SessionSettings.Faults == 1 && InventoryResourceHooks.Available, "Partial unload did not hold native guards"); });
Check("Run identity change aborts restore and finalizer clears the context", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); s.BeforeInitializeRead = () => SaveManager.CurrentRun = new(); Throws(() => s.RunInitialize()); Assert(s.ReadSlots == 0 && p.Inventory.StorageWrites == 0, "Stale run was mutated"); s.BeforeInitializeRead = null; s.RunInitialize(); Assert(s.ReadSlots == 24, "Failed context leaked into retry"); });
Check("Reused avatar restart with a fresh native save reapplies policy once", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); SaveManager.CurrentRun = new(); ResourceRuntime.Managed.Add(ResourceKind.Slots); ResourceRuntime.Apply = (player, kind, min) => { player.Inventory.CurrentInventoryStorage = 48; player.customStats[ResourceCatalog.Get(kind).Marker] = 24; }; s.RunInitialize(); Assert(s.ReadSlots == 48 && ResourceRuntime.Calls == 1 && ResourceRuntime.Restored == 0, "Old run checkpoint leaked into restart"); });
Check("Inventory checkpoint restore cannot cross an unresolved write journal", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; s.SaveCurrentSessionData(); p.Inventory.CurrentInventoryStorage = 24; p.customStats.Clear(); SessionSettings.ResourceWritesBlocked = true; Throws(() => s.RunInitialize()); Assert(p.Inventory.CurrentInventoryStorage == 24 && s.ReadSlots == 0, "Checkpoint wrote across pending recovery"); });
Check("Inventory restore detects generation change with reused save object", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); s.BeforeInitializeRead = () => SessionSettings.ResourceGeneration++; Throws(() => s.RunInitialize()); Assert(s.ReadSlots == 0, "Reused run object hid generation change"); });
Check("Inventory unload refuses another unresolved write journal", () => { var p = new PlayerAvatar(); _ = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; SessionSettings.ResourceWritesBlocked = true; Throws(() => InventoryResourceHooks.Uninstall()); Assert(p.Inventory.StorageWrites == 0 && InventoryResourceHooks.Available, "Unload crossed recovery journal"); });
Check("Managed owner still joining blocks unload before resize", () => { var p = new PlayerAvatar(); _ = new PlayerSpawner(p) { Ready = false }; p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; Throws(() => InventoryResourceHooks.Uninstall()); Assert(p.Inventory.StorageWrites == 0 && InventoryResourceHooks.Available, "Initializing owned inventory unloaded"); });
Check("Safe unload restores native capacity, checkpoints zero ownership, unpatches", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.Inventory.CurrentInventoryStorage = 36; p.customStats[ResourceCatalog.Get(ResourceKind.Slots).Marker] = 12; InventoryResourceHooks.Uninstall(); Assert(!InventoryResourceHooks.Available && p.Inventory.CurrentInventoryStorage == 24 && !p.customStats.ContainsKey(ResourceCatalog.Get(ResourceKind.Slots).Marker), "Safe unload incomplete"); Assert(SaveManager.CurrentRun.Values.Values.OfType<int>().Contains(24) && SaveManager.CurrentRun.Values.Values.OfType<int>().Contains(0), "Reset checkpoint missing"); Assert(s.SaveCalls == 1, "Native saved item positions were not refreshed"); });
Check("Talent saved-run reconnect restores budget with no current policy", () => { ResourceBudgetHooks.Install(); var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.maxPassivePoint = 5; p.customStats.Clear(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); Assert(p.maxPassivePoint == 20 && p.NativeLoadCalls == 1 && p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] == 15 && ResourceRuntime.Restored == 1, "Saved managed selections lost their budget"); });
Check("Talent reused avatar checkpoint does not compound contribution", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); Assert(p.maxPassivePoint == 20 && p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] == 15, "Talent restore compounded"); });
Check("Talent checkpoint preserves native cap gain on reconnect", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.maxPassivePoint = 7; p.customStats.Clear(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); Assert(p.maxPassivePoint == 22 && p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] == 15, "Native talent gain overwritten"); });
Check("Talent checkpoint does not cross GUID or new run boundaries", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.maxPassivePoint = 5; p.customStats.Clear(); s.playerGuid = "another-owner"; p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 0, "Talent checkpoint crossed owner"); s.playerGuid = "player-guid"; SaveManager.CurrentRun = new(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 0, "Talent checkpoint crossed run"); });
Check("Managed saved talent load above restored checkpoint fails explicitly", () => { var p = new PlayerAvatar { maxPassivePoint = 10 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 5; s.SaveCurrentSessionData(); p.maxPassivePoint = 5; p.customStats.Clear(); Throws(() => p.LoadPassiveStatOnServer(new[] { Pick(1, 20) })); Assert(p.NativeLoadCalls == 0 && p.maxPassivePoint == 10, "Insufficient restored cap silently clamped native picks"); });
Check("Talent menu reload cannot undo an explicit reduction after initial restore", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); p.maxPassivePoint = 5; p.customStats.Clear(); p.LoadPassiveStatOnServer(new[] { Pick(1, 5) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 1, "Stale checkpoint reversed explicit reduction"); });
Check("New checkpoint created during a run is not treated as first-load restore", () => { var p = new PlayerAvatar(); var s = new PlayerSpawner(p); p.LoadPassiveStatOnServer(new[] { Pick(1, 5) }); p.maxPassivePoint = 20; p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.maxPassivePoint = 5; p.customStats.Clear(); p.LoadPassiveStatOnServer(new[] { Pick(1, 5) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 0, "Fresh avatar later reapplied its own old save"); });
Check("Talent checkpoint cannot cross an unresolved write journal", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.maxPassivePoint = 5; p.customStats.Clear(); SessionSettings.ResourceWritesBlocked = true; Throws(() => p.LoadPassiveStatOnServer(new[] { Pick(1, 20) })); Assert(p.maxPassivePoint == 5 && p.NativeLoadCalls == 0, "Talent restore crossed recovery journal"); });
Check("First-departure generation event cannot restore stale talent checkpoint", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); p.maxPassivePoint = 5; p.customStats.Clear(); SessionSettings.ResourceGeneration++; p.LoadPassiveStatOnServer(new[] { Pick(1, 5) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 1, "Same-run generation event resurrected stale budget"); });
Check("Uninstall and reinstall on the same avatar does not resurrect talent checkpoint", () => { var p = new PlayerAvatar { maxPassivePoint = 20 }; var s = new PlayerSpawner(p); p.customStats[ResourceCatalog.Get(ResourceKind.Talents).Marker] = 15; s.SaveCurrentSessionData(); p.LoadPassiveStatOnServer(new[] { Pick(1, 20) }); p.maxPassivePoint = 5; p.customStats.Clear(); ResourceBudgetHooks.Uninstall(); ResourceBudgetHooks.Install(); p.LoadPassiveStatOnServer(new[] { Pick(1, 5) }); Assert(p.maxPassivePoint == 5 && ResourceRuntime.Restored == 1, "Hook reinstall resurrected stale budget"); });
Check("Talent hooks uninstall after checkpoint tests", () => ResourceBudgetHooks.Uninstall());
Console.WriteLine($"{passed} passed; {failed} failed.");
Environment.ExitCode = failed == 0 ? 0 : 1;
