using Mirror;
using Mirror.FizzySteam;
using SephiriaOne;
using Steamworks;
using UnityEngine;

int checks = 0;
void Check(bool ok, string reason) { if (!ok) throw new Exception(reason); checks++; }
DisconnectDiagnostics.Install();
DisconnectDiagnostics.Install();
var server = new NextServer();
server.Lose(1);
Check(server.NativeCloses == 1, "Diagnostics changed native close count");
Check(Debug.Lines.Any(l => l.Contains("1001") && l.Contains("fixture reason") && l.Contains("conn=1")), "Lost Steam close reason before native overwrite");
Check(Debug.Lines.Count(l => l.Contains("fixture reason")) == 1, "Duplicate install duplicated callback");
SteamNetworkingSockets.Available = false;
server.Lose(3);
Check(server.NativeCloses == 2 && Debug.Lines.Any(l => l.Contains("conn=3") && l.Contains("unavailable")), "Missing unavailable-info fallback");
SteamNetworkingSockets.Throw = true;
server.Lose(4);
Check(server.NativeCloses == 3, "Steam diagnostic failure blocked native close");
server.Disconnect(2);
Check(server.NativeCloses == 4 && Debug.Lines.Any(l => l.Contains("server-requested") && l.Contains("conn=2")), "Host-requested close is not distinguished");
var manager = new HorayNetworkManager();
var connection = new NetworkConnectionToClient();
manager.OnServerDisconnect(connection);
Check(connection.identity == null && manager.NativeRemovals == 1 && SessionSettings.Reads == 1, "Diagnostic blocked destruction or did not read before it");
Check(Debug.Lines.Any(l => l.Contains("snapshot player=78")), "Missing departing player's sync context");
SessionSettings.Throw = true;
manager.OnServerDisconnect(new());
Check(manager.NativeRemovals == 2, "Snapshot exception interrupted native cleanup");
manager.OnServerDisconnect(null);
Check(manager.NativeRemovals == 3, "Null connection interrupted native cleanup");
Debug.Throw = true;
server.Lose(5);
manager.OnServerDisconnect(new());
Check(server.NativeCloses == 5 && manager.NativeRemovals == 4, "Logger failure escaped a diagnostic hook");
Debug.Throw = false;
Check(!DisconnectDiagnostics.OneLine("line1\nline2\t\0").Contains('\n'), "Transport detail contains injectable log newline");
Check(DisconnectDiagnostics.OneLine(new string('x', 1000)).Length <= 256, "Unbounded transport detail");
DisconnectDiagnostics.Uninstall();
int lines = Debug.Lines.Count;
server.Lose(1);
manager.OnServerDisconnect(new());
Check(Debug.Lines.Count == lines && server.NativeCloses == 6 && manager.NativeRemovals == 5, "Hooks survived uninstall");
Console.WriteLine($"Passed {checks} disconnect-diagnostic boundary checks (fixtures, no live transport).");
