namespace UnityEngine { public class Object { public static implicit operator bool(Object o)=>!ReferenceEquals(o,null); } }
namespace Mirror { public static class NetworkServer { public static bool active=true; } public class NetworkConnectionToClient { public NetworkIdentity identity; } public class NetworkIdentity:UnityEngine.Object { public PlayerAvatar Player; public T GetComponent<T>() where T:class=>Player as T; } }
public class SaveData { public Dictionary<string,string> Data=new();public bool ContainsKey(string k)=>Data.ContainsKey(k);public int GetInt(string k,int fallback=0)=>Data.TryGetValue(k,out var v)?int.Parse(v):fallback;public string GetString(string k,string fallback="")=>Data.GetValueOrDefault(k,fallback);public void SetInt(string k,int v)=>Data[k]=v.ToString();public void SetString(string k,string v)=>Data[k]=v; }
public static class SaveManager { public static SaveData CurrentRun=new(); }
public class TreeShopItemStorage:UnityEngine.Object { public int Seed=200; public int GettStartingMoney()=>Seed; }
public class UnitAvatar:UnityEngine.Object { public bool isServer=true;public int currentMoney;public int Bonus;public TreeShopItemStorage Tree=new();public Action<int> OnMoneyWrite;public int NetworkcurrentMoney { set {currentMoney=value;OnMoneyWrite?.Invoke(value);} }public int GetCustomStatUnsafe(string id)=>Bonus;public void AddMoney(int amount)=>NetworkcurrentMoney=checked(currentMoney+amount);public T GetComponent<T>() where T:class=>Tree as T; }
public class PlayerAvatar:UnitAvatar { public PlayerSpawner spawner;public int maxRerollDice=3;public int rerollDice;public Dictionary<string,int> customStats=new();public int NetworkmaxRerollDice {set=>maxRerollDice=value;}public int NetworkrerollDice{set=>rerollDice=value;} }
public class PlayerSpawner:UnityEngine.Object {public static List<PlayerSpawner> MultiplayerList=new();public PlayerAvatar PlayerAvatar;public int currentPlayerIdxForSave;public string playerGuid="one";private bool Initialize(int a,string b,string c,int d)=>true;}
public class DungeonManager:UnityEngine.Object {public static DungeonManager Instance=new();public Dictionary<string,int> dungeonEnvironment=new();public void LoadStageAndMove(string name){} }
public class HorayNetworkManager { public void OnServerDisconnect(Mirror.NetworkConnectionToClient conn){} }
namespace SephiriaOne { internal static class ResourceRuntime {public static Dictionary<ResourceKind,ResourceSetting> Policy=new();public static List<string> Warnings=new();public static bool TryGetSetting(ResourceKind kind,out ResourceSetting setting)=>Policy.TryGetValue(kind,out setting);public static void Report(string message)=>Warnings.Add(message);} }
