using System.IO.Compression;
using System.Net;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json.Linq;
using SephiriaOne;

internal static class Program
{
    private static int passed, failed;
    private const string Url = "https://github.com/preco21/SephiriaOne/releases/download/v1.2.3/SephiriaOne.zip";
    private const string Metadata = "{\"modName\":\"SephiriaOne\",\"modVersion\":\"1.2.3\",\"dllFile\":\"SephiriaOne.dll\",\"entryClass\":\"SephiriaOne.Entry\"}";
    private static async Task Main()
    {
        await Test("release normalizes version and digest", () => { var r = new UpdateRelease(new Version(1,2,3,0), "v1.2.3", Url, new string('A',64), 4); Equal(new Version(1,2,3), r.Version); Equal(new string('a',64),r.Sha256); return Task.CompletedTask; });
        foreach (var tag in new[] { "v1.2", "v1.2.3-beta", "1.2.3", "v01.2.3", "v1.2.3.0" })
            await Test("rejects tag " + tag, () => Reject(() => new UpdateRelease(new Version(1,2,3), tag, Url, new string('a',64), 4)));
        await Test("rejects foreign asset URL", () => Reject(() => new UpdateRelease(new Version(1,2,3), "v1.2.3", Url.Replace("preco21", "attacker"), new string('a',64), 4)));
        await Test("parses three part local version", () => { True(UpdateRelease.TryParseVersion("0.37.2", out var v)); Equal(new Version(0,37,2),v); True(!UpdateRelease.TryParseVersion("0.37.2-beta",out _)); return Task.CompletedTask; });
        await Test("selects stable named ZIP", async () => { using var c = Client(Json()); var r = await c.CheckAsync(default); Equal("v1.2.3",r.Tag); Equal(4L,r.Size); });
        await Test("no published stable release", async () => { using var c = Client("", HttpStatusCode.NotFound); Equal(null,await c.CheckAsync(default)); });
        await Test("prerelease excluded", async () => { using var c = Client(Json().Replace("\"prerelease\":false", "\"prerelease\":true")); Equal(null,await c.CheckAsync(default)); });
        foreach (var value in new[] { "{", Json().Replace("sha256:","md5:"), Json().Replace("\"draft\":false,", ""), Json().Replace("\"size\":4", "\"size\":16777217"), Json().Replace("\"assets\":[", "\"assets\":[" + Asset() + ",") })
            await Test("rejects malformed release " + value.Length, async () => { using var c = Client(value); await RejectAsync(() => c.CheckAsync(default)); });
        await Test("rejects oversized JSON", async () => { using var c = Client(new string(' ',262145)); await RejectAsync(() => c.CheckAsync(default)); });
        await Test("download enforces size", async () => { using var c = Client("12345"); await RejectAsync(() => c.DownloadAsync(Release(Encoding.UTF8.GetBytes("1234")),default)); });
        await Test("download enforces hash", async () => { using var c = Client("abcd"); await RejectAsync(() => c.DownloadAsync(Release(Encoding.UTF8.GetBytes("1234")),default)); });
        await Test("download verifies valid bytes", async () => { using var c = Client("1234"); var b = Encoding.UTF8.GetBytes("1234"); True((await c.DownloadAsync(Release(b),default)).SequenceEqual(b)); });
        await Test("foreign redirect rejected", async () => { using var c = new GitHubReleaseClient(new Handler(_ => { var r = new HttpResponseMessage(HttpStatusCode.Redirect); r.Headers.Location = new Uri("https://attacker.example/file"); return r; })); await RejectAsync(() => c.DownloadAsync(Release(new byte[4]),default)); });
        await Test("cancellation reaches HTTP", async () => { using var c = Client(Json()); using var token = new CancellationTokenSource(); token.Cancel(); await RejectAsync(() => c.CheckAsync(token.Token)); });
        await Test("installs immutable DLL and atomically switches metadata", () => WithInstall((folder,installer) => { var old = File.ReadAllBytes(Path.Combine(folder,"SephiriaOne.dll")); var b = Package(); installer.Install(Release(b),b,default); Equal(new Version(1,2,3),installer.ReadInstalledVersion()); Equal("SephiriaOne.1.2.3.dll",JObject.Parse(File.ReadAllText(Path.Combine(folder,"metadata.json")))["dllFile"].Value<string>()); True(old.SequenceEqual(File.ReadAllBytes(Path.Combine(folder,"SephiriaOne.dll")))); True(File.Exists(Path.Combine(folder,"SephiriaOne.1.2.3.dll"))); True(Directory.GetFiles(folder,"*.previous.json").Length == 1); }));
        foreach (var extra in new[] { "../outside.dll", "/outside.dll", "x.exe", "folder/", "metadata.json", "sephiriaone.dll" })
            await Test("hostile ZIP preserves metadata " + extra, () => WithInstall((folder,installer) => { var initial = File.ReadAllBytes(Path.Combine(folder,"metadata.json")); var b = Package(extra:extra); MustThrow(() => installer.Install(Release(b),b,default)); True(initial.SequenceEqual(File.ReadAllBytes(Path.Combine(folder,"metadata.json")))); }));
        foreach (var meta in new[] { Metadata.Replace("SephiriaOne.Entry","Wrong.Entry"),Metadata.Replace("1.2.3","1.2.4"),Metadata.Replace("SephiriaOne.dll","other.dll"),Metadata.Replace("\"modName\":\"SephiriaOne\"","\"modName\":\"Foreign\""),"{",new string(' ',65537) })
            await Test("invalid package metadata preserves active metadata " + meta.Length, () => WithInstall((folder,installer) => { var initial = File.ReadAllBytes(Path.Combine(folder,"metadata.json")); var b = Package(metadata:meta); MustThrow(() => installer.Install(Release(b),b,default)); True(initial.SequenceEqual(File.ReadAllBytes(Path.Combine(folder,"metadata.json")))); }));
        await Test("invalid DLL preserves metadata", () => WithInstall((folder,installer) => { var b = Package(dll:new byte[]{1,2,3}); MustThrow(() => installer.Install(Release(b),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("hash mismatch preserves metadata", () => WithInstall((folder,installer) => { var b = Package(); MustThrow(() => installer.Install(Release(new byte[]{1}),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("equal pending version rejected", () => WithInstall((folder,installer) => { var b = Package(); installer.Install(Release(b),b,default); MustThrow(() => installer.Install(Release(b),b,default)); Equal(new Version(1,2,3),installer.ReadInstalledVersion()); }));
        await Test("existing version DLL is never overwritten", () => WithInstall((folder,installer) => { var path = Path.Combine(folder,"SephiriaOne.1.2.3.dll"); File.WriteAllText(path,"keep"); var b = Package(); MustThrow(() => installer.Install(Release(b),b,default)); Equal("keep",File.ReadAllText(path)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("cancelled installation preserves metadata", () => WithInstall((folder,installer) => { var b = Package(); MustThrow(() => installer.Install(Release(b),b,new CancellationToken(true))); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("running DLL outside folder rejected", () => { var folder = NewFolder(); try { MustThrow(() => new UpdateInstaller(folder,typeof(Program).Assembly.Location)); } finally { Directory.Delete(folder,true); } return Task.CompletedTask; });
        await Test("rate limit exposes retry-after timestamp", async () => { var retry=DateTimeOffset.UtcNow.AddMinutes(5); using var c=new GitHubReleaseClient(new Handler(_=> { var response=new HttpResponseMessage((HttpStatusCode)429); response.Headers.RetryAfter=new System.Net.Http.Headers.RetryConditionHeaderValue(retry); return response; })); try { await c.CheckAsync(default); throw new Exception("Expected rate limit"); } catch(UpdateRateLimitException e) { True(Math.Abs((e.RetryAfter-retry).TotalSeconds)<1); } });
        await Test("rate limit uses reset timestamp", async () => { var retry=DateTimeOffset.UtcNow.AddMinutes(5).ToUnixTimeSeconds(); using var c=new GitHubReleaseClient(new Handler(_=> { var response=new HttpResponseMessage(HttpStatusCode.Forbidden); response.Headers.TryAddWithoutValidation("X-RateLimit-Reset",retry.ToString()); return response; })); try { await c.CheckAsync(default); throw new Exception("Expected rate limit"); } catch(UpdateRateLimitException e) { Equal(retry,e.RetryAfter.ToUnixTimeSeconds()); } });
        await Test("ETag validates cached release on 304", async () => { var calls=0; using var c=new GitHubReleaseClient(new Handler(request=> { if(calls++==0) { var r=new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(Json())}; r.Headers.ETag=new System.Net.Http.Headers.EntityTagHeaderValue("\"abc\""); return r; } Equal("\"abc\"",request.Headers.IfNoneMatch.Single().ToString()); return new HttpResponseMessage(HttpStatusCode.NotModified); })); var initial=await c.CheckAsync(default); True(ReferenceEquals(initial,await c.CheckAsync(default))); });
        await Test("uncached 304 rejected", async () => { using var c=Client("",HttpStatusCode.NotModified); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("allowed download redirect verifies body", async () => { var calls=0; using var c=new GitHubReleaseClient(new Handler(request=> { if(calls++==0) { var r=new HttpResponseMessage(HttpStatusCode.Redirect); r.Headers.Location=new Uri("https://release-assets.githubusercontent.com/file?sig=example"); return r; } Equal("release-assets.githubusercontent.com",request.RequestUri.Host); return new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("1234")}; })); True((await c.DownloadAsync(Release(Encoding.UTF8.GetBytes("1234")),default)).SequenceEqual(Encoding.UTF8.GetBytes("1234"))); });
        foreach(var redirect in new[] { "http://release-assets.githubusercontent.com/file", "https://evil.release-assets.githubusercontent.com/file", "https://user:secret@release-assets.githubusercontent.com/file", "https://release-assets.githubusercontent.com:444/file", "https://github.com/attacker/repo/releases/download/v1.2.3/SephiriaOne.zip" })
            await Test("redirect boundary " + redirect, async () => { using var c=new GitHubReleaseClient(new Handler(_=> { var r=new HttpResponseMessage(HttpStatusCode.Redirect); r.Headers.Location=new Uri(redirect); return r; })); await RejectAsync(()=>c.DownloadAsync(Release(new byte[4]),default)); });
        await Test("draft excluded", async () => { using var c=Client(Json().Replace("\"draft\":false","\"draft\":true")); Equal(null,await c.CheckAsync(default)); });
        await Test("duplicate JSON fields rejected", async () => { using var c=Client(Json().Replace("\"draft\":false","\"draft\":true,\"draft\":false")); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("missing asset rejected", async () => { using var c=Client(Json().Replace(Asset(),"")); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("uncached JSON is not reused after 404", async () => { var calls=0; using var c=new GitHubReleaseClient(new Handler(_=> { if(calls++==0) { var r=new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(Json())}; r.Headers.ETag=new System.Net.Http.Headers.EntityTagHeaderValue("\"abc\""); return r; } return new HttpResponseMessage(calls==2?HttpStatusCode.NotFound:HttpStatusCode.NotModified); })); await c.CheckAsync(default); Equal(null,await c.CheckAsync(default)); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("downgrade is rejected", () => WithInstall((folder,installer)=> { File.WriteAllText(Path.Combine(folder,"metadata.json"),Metadata.Replace("1.2.3","2.0.0")); var b=Package(); MustThrow(()=>installer.Install(Release(b),b,default)); Equal(new Version(2,0,0),installer.ReadInstalledVersion()); }));
        await Test("cross-process transaction lock blocks install", () => WithInstall((folder,installer)=> { using var held=new FileStream(Path.Combine(folder,".one-update.lock"),FileMode.OpenOrCreate,FileAccess.ReadWrite,FileShare.None); var b=Package(); MustThrow(()=>installer.Install(Release(b),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("locked metadata prevents commit and retains complete immutable DLL", () => WithInstall((folder,installer)=> { var path=Path.Combine(folder,"metadata.json"); var before=File.ReadAllBytes(path); using(var held=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read)) { var b=Package(); MustThrow(()=>installer.Install(Release(b),b,default)); } True(before.SequenceEqual(File.ReadAllBytes(path))); True(File.Exists(Path.Combine(folder,"SephiriaOne.1.2.3.dll"))); }));
        await Test("ZIP symlink is rejected", () => WithInstall((folder,installer)=> { var b=Package(symlink:true); MustThrow(()=>installer.Install(Release(b),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("oversized expanded DLL is rejected", () => WithInstall((folder,installer)=> { var b=Package(dll:new byte[32*1024*1024+1]); MustThrow(()=>installer.Install(Release(b),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("DLL version mismatch is rejected", () => WithInstall((folder,installer)=> { var b=Package(metadata:Metadata.Replace("1.2.3","1.2.4")); var r=new UpdateRelease(new Version(1,2,4),"v1.2.4",Url.Replace("v1.2.3","v1.2.4"),Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant(),b.Length); MustThrow(()=>installer.Install(r,b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        foreach(var json in new[] { Json().Replace("\"draft\":false","draft:false"), Json().Replace("\"draft\":false","'draft':false"), Json().Replace("\"draft\":false","\"draft\":false/*comment*/"),Json().Replace("\"prerelease\":false","\"prerelease\":false,\"x\":NaN"),Json().Replace("]}","],}") })
            await Test("nonstandard JSON is rejected " + json.Length, async ()=> { using var c=Client(json); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("manual metadata mutation during staging is detected", ()=>WithInstall((folder,installer)=> { var changed=Metadata.Replace("1.2.3","1.1.0"); Exception watcherError=null; using var watcher=new FileSystemWatcher(folder,".one-update-*.dll"); using var signal=new ManualResetEventSlim(); watcher.Created+=(_,__)=> { try { File.WriteAllText(Path.Combine(folder,"metadata.json"),changed); } catch(Exception e) { watcherError=e; } finally { signal.Set(); } }; watcher.EnableRaisingEvents=true; var dll=new byte[32*1024*1024]; File.ReadAllBytes(typeof(Program).Assembly.Location).CopyTo(dll,0); var b=Package(dll:dll); Exception failure=null; try { installer.Install(Release(b),b,default); } catch(Exception e) { failure=e; } True(signal.Wait(TimeSpan.FromSeconds(3))); if(watcherError!=null) throw watcherError; True(failure is IOException && failure.Message.Contains("metadata changed")); Equal(changed,File.ReadAllText(Path.Combine(folder,"metadata.json"))); True(File.Exists(Path.Combine(folder,"SephiriaOne.1.2.3.dll"))); }));
        await Test("pending old DLL remains valid and backup contains old metadata", ()=>WithInstall((folder,installer)=> { var before=File.ReadAllBytes(Path.Combine(folder,"metadata.json")); var b=Package(); installer.Install(Release(b),b,default); var backup=Directory.GetFiles(folder,"*.previous.json").Single(); True(before.SequenceEqual(File.ReadAllBytes(backup))); var active=File.ReadAllBytes(Path.Combine(folder,"SephiriaOne.1.2.3.dll")); True(active.SequenceEqual(File.ReadAllBytes(typeof(Program).Assembly.Location))); Equal("SephiriaOne",AssemblyName.GetAssemblyName(Path.Combine(folder,"SephiriaOne.dll")).Name); }));
        await Test("other assembly identity is rejected", ()=>WithInstall((folder,installer)=> { var assembly=AssemblyName.GetAssemblyName(typeof(JObject).Assembly.Location); var version=new Version(assembly.Version.Major,assembly.Version.Minor,assembly.Version.Build); var b=Package(metadata:Metadata.Replace("1.2.3",version.ToString(3)),dll:File.ReadAllBytes(typeof(JObject).Assembly.Location)); var tag="v"+version.ToString(3); var r=new UpdateRelease(version,tag,Url.Replace("v1.2.3",tag),Convert.ToHexString(SHA256.HashData(b)).ToLowerInvariant(),b.Length); MustThrow(()=>installer.Install(r,b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("unexpected metadata DLL path rejected", ()=>WithInstall((folder,installer)=> { File.WriteAllText(Path.Combine(folder,"metadata.json"),Metadata.Replace("SephiriaOne.dll","../SephiriaOne.dll").Replace("1.2.3","1.0.0")); MustThrow(()=>installer.ReadInstalledVersion()); var b=Package(); MustThrow(()=>installer.Install(Release(b),b,default)); }));
        await Test("noncanonical package filename rejected", ()=>WithInstall((folder,installer)=> { using var ms=new MemoryStream(); using(var zip=new ZipArchive(ms,ZipArchiveMode.Create,true)) { Write(zip,"metadata.json",Encoding.UTF8.GetBytes(Metadata)); Write(zip,"./SephiriaOne.dll",File.ReadAllBytes(typeof(Program).Assembly.Location)); } var b=ms.ToArray(); MustThrow(()=>installer.Install(Release(b),b,default)); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); }));
        await Test("repeated redirects are bounded", async ()=> { var calls=0; using var c=new GitHubReleaseClient(new Handler(_=> { calls++; var r=new HttpResponseMessage(HttpStatusCode.Redirect); r.Headers.Location=new Uri("https://release-assets.githubusercontent.com/file"); return r; })); await RejectAsync(()=>c.DownloadAsync(Release(new byte[4]),default)); Equal(5,calls); });
        await Test("chunked download is bounded without declared length", async ()=> { using var c=new GitHubReleaseClient(new Handler(_=>new HttpResponseMessage(HttpStatusCode.OK){Content=new StreamContent(new MemoryStream(new byte[10]))})); await RejectAsync(()=>c.DownloadAsync(Release(new byte[4]),default)); });
        await Test("valid JSON string escapes accepted", async ()=> { using var c=Client(Json().Replace("\"draft\":false","\"draft\":false,\"note\":\"Unicode \\uD55C, escape \\n and slash \\/\"")); Equal("v1.2.3",(await c.CheckAsync(default)).Tag); });
        await Test("in-flight network cancellation is observed", async ()=> { using var c=new GitHubReleaseClient(new BlockingHandler()); using var token=new CancellationTokenSource(); token.CancelAfter(20); await RejectAsync(()=>c.CheckAsync(token.Token)); });
        await Test("literal used as unquoted JSON property rejected", async ()=> { using var c=Client(Json().Replace("\"draft\":false","\"draft\":false,true:null")); await RejectAsync(()=>c.CheckAsync(default)); });
        await Test("cancellation during staging preserves metadata", ()=>WithInstall((folder,installer)=> { using var cancellation=new CancellationTokenSource(); using var watcher=new FileSystemWatcher(folder,".one-update-*.dll"); watcher.Created+=(_,__)=>cancellation.Cancel(); watcher.EnableRaisingEvents=true; var dll=new byte[32*1024*1024]; File.ReadAllBytes(typeof(Program).Assembly.Location).CopyTo(dll,0); var b=Package(dll:dll); Exception failure=null; try { installer.Install(Release(b),b,cancellation.Token); } catch(Exception e) { failure=e; } True(failure is OperationCanceledException); Equal(new Version(1,0,0),installer.ReadInstalledVersion()); True(!File.Exists(Path.Combine(folder,"SephiriaOne.1.2.3.dll"))); }));
        await Test("manual selection of staged DLL survives failed commit cleanup", ()=>WithInstall((folder,installer)=> {
            var selected=Metadata.Replace("SephiriaOne.dll","SephiriaOne.1.2.3.dll");
            var paddedMetadata=Metadata.Replace("\"modName\":", "\"padding\":\""+new string('x',60000)+"\",\"modName\":");
            Exception watcherError=null;
            using var signal=new ManualResetEventSlim();
            using var watcher=new FileSystemWatcher(folder,"SephiriaOne.1.2.3.dll");
            watcher.Renamed+=(_,__)=> { try { File.WriteAllText(Path.Combine(folder,"metadata.json"),selected); } catch(Exception e) { watcherError=e; } finally { signal.Set(); } };
            watcher.EnableRaisingEvents=true;
            var b=Package(metadata:paddedMetadata);
            Exception failure=null;
            try { installer.Install(Release(b),b,default); } catch(Exception e) { failure=e; }
            True(signal.Wait(TimeSpan.FromSeconds(3)));
            if(watcherError!=null) throw watcherError;
            True(failure is IOException && failure.Message.Contains("metadata changed"));
            Equal(selected,File.ReadAllText(Path.Combine(folder,"metadata.json")));
            if(!File.Exists(Path.Combine(folder,"SephiriaOne.1.2.3.dll"))) throw new Exception("Cleanup deleted the DLL selected by concurrent metadata");
            Equal(new Version(1,2,3),installer.ReadInstalledVersion());
            True(Directory.GetFiles(folder,".one-update-*.dll").Length==0);
            True(Directory.GetFiles(folder,".one-update-*.json").Length==0);
        }));
        Console.WriteLine($"Update core: {passed} passed; {failed} failed"); if(failed != 0) Environment.ExitCode = 1;
    }
    private static async Task Test(string name, Func<Task> test) { try { await test(); passed++; } catch(Exception e) { failed++; Console.WriteLine("FAIL " + name + ": " + e.GetType().Name + " " + e.Message); } }
    private static void True(bool value) { if(!value) throw new Exception("Expected true"); }
    private static void Equal<T>(T expected,T actual) { if(!Equals(expected,actual)) throw new Exception($"Expected {expected}; got {actual}"); }
    private static void MustThrow(Action action) { try { action(); } catch(Exception e) when (e is not NotImplementedException) { return; } throw new Exception("Expected validation rejection"); }
    private static Task Reject(Action action) { MustThrow(action); return Task.CompletedTask; }
    private static async Task RejectAsync(Func<Task> action) { try { await action(); } catch(Exception e) when (e is not NotImplementedException) { return; } throw new Exception("Expected validation rejection"); }
    private static string Asset() => "{\"name\":\"SephiriaOne.zip\",\"size\":4,\"digest\":\"sha256:" + new string('a',64) + "\",\"browser_download_url\":\"" + Url + "\"}";
    private static string Json() => "{\"tag_name\":\"v1.2.3\",\"draft\":false,\"prerelease\":false,\"assets\":[" + Asset() + "]}";
    private static UpdateRelease Release(byte[] bytes) => new(new Version(1,2,3),"v1.2.3",Url,Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(),bytes.Length);
    private static GitHubReleaseClient Client(string body,HttpStatusCode code=HttpStatusCode.OK) => new(new Handler(_ => new HttpResponseMessage(code) { Content=new StringContent(body) }));
    private sealed class Handler(Func<HttpRequestMessage,HttpResponseMessage> respond) : HttpMessageHandler { protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken token) { token.ThrowIfCancellationRequested(); return Task.FromResult(respond(request)); } }
    private sealed class BlockingHandler : HttpMessageHandler { protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken token) { await Task.Delay(Timeout.Infinite,token); throw new Exception("Unreachable"); } }
    private static string NewFolder() { var p = Path.Combine(Path.GetTempPath(),"SephiriaOne-update-tests-"+Guid.NewGuid().ToString("N")); Directory.CreateDirectory(p); return p; }
    private static Task WithInstall(Action<string,UpdateInstaller> action) { var p = NewFolder(); try { File.Copy(typeof(Program).Assembly.Location,Path.Combine(p,"SephiriaOne.dll")); File.WriteAllText(Path.Combine(p,"metadata.json"),Metadata.Replace("1.2.3","1.0.0")); action(p,new UpdateInstaller(p,Path.Combine(p,"SephiriaOne.dll"))); } finally { Directory.Delete(p,true); } return Task.CompletedTask; }
    private static byte[] Package(string metadata=Metadata,byte[] dll=null,string extra=null,bool symlink=false) { using var ms = new MemoryStream(); using(var zip = new ZipArchive(ms,ZipArchiveMode.Create,true)) { Write(zip,"metadata.json",Encoding.UTF8.GetBytes(metadata)); var dllEntry=Write(zip,"SephiriaOne.dll",dll??File.ReadAllBytes(typeof(Program).Assembly.Location)); if(symlink) dllEntry.ExternalAttributes=unchecked((int)0xA1FF0000); if(extra != null) Write(zip,extra,new byte[]{1}); } return ms.ToArray(); }
    private static ZipArchiveEntry Write(ZipArchive zip,string name,byte[] bytes) { var entry=zip.CreateEntry(name); using var output=entry.Open(); output.Write(bytes); return entry; }
}
